### ISSUE TITLE
Set Bool minimum_number_should_match to 1

### ISSUE THREAD

**Issue by Mopster** [polyfractal/sherlock#27]
I would propose to set the Bool's minimum_number_should_match to default 1. It would seem more general that only 1 match in the doc would be enough to have it as a result.

edit : Thinking on it further, how is this variable used for each method ?
### must

Every query in the $value array parameter should have at lease 'minimum_number_should_match' before the result is returned.
### should

Is the 'minimum_number_should_match' spread over all queries in the $value array, or should there be at least 1 query which has 'minimum_number_should_match' matches.
### must_not

Every query in the $value array should have less than 'minimum_number_should_match' matches ?

**Comment by polyfractal** [comment]
minimum_number_should_match only applies to Should clauses in Bools.  The [ES docs](http://www.elasticsearch.org/guide/reference/query-dsl/bool-query/) briefly mention it, but don't really go into much detail.

The parameter's behavior is applied when evaluating documents.  So in this situation:
- Should clause
  - Five Term queries
  - minimum_number_should_match = 2

A document must satisfy at least two of the five Term queries before being returned as a match.  If you set minimum_number_should_match = 5, then you effectively turned the Should clause into a Must clause in this particular scenario, since the document must match all the Term queries.

Edit: a quirk of the ES Query DSL, the min_number_should_match parameter sits on the same "scope level" as the must/should/must_not parameters, which is why it appears to apply to any of them.  You only need to set it once, and it only applies to Should.

Regarding the default, I stole the default value from the [Perl Client](http://search.cpan.org/~drtech/ElasticSearch-SearchBuilder-0.18/lib/ElasticSearch/SearchBuilder.pm#-bool), which is the best authoritative source for defaults that I've found (since the ES docs don't mention any defaults, unforutnately).

However, I recently discovered that simply passing Null to ES is acceptable and falls back onto the internal ES defaults, so I've been considering retrofiting all the queries/filters to pass Null instead of hardcoded defaults.

**Comment by Mopster** [comment]
I think using the ES default would be a good idea. Now it has to be overruled each time a should query is created to use the default ES settings. And I think having the setting on 1 (which is default ES) would be the most used setting in general queries.

**Comment by polyfractal** [comment]
Yeah, I agree with you.  I'll open an issue to retrofit the queries with Nulls instead of hardcoded defaults.  Will take a little time to get them all switched over.

**Comment by polyfractal** [comment]
Closing this since the new issues cover the problems more specifically
