### ISSUE TITLE
facet filter

### ISSUE THREAD

**Issue by timglabisch** [polyfractal/sherlock#80]
is there no way to filter facets?

```
$facets = Sherlock::facetBuilder()->Terms()
            ->fields('whatever')
            ->all_terms(true)
            ->facet_filter($filter);
```

works, but if i just use filter it is ignored.
Debugging the code it looks like filter is completly missing here.

is there any way to run a simple facet that is filtered?

**Comment by polyfractal** [comment]
Sorry for the delay on this, been traveling for work a lot.

How do you mean a "simple facet that is filtered" ?  A `facet_filter` will filter the facet context (e.g. not the search results), a `filtered_query` will filter both the search results and the facet results, and a `top level filter` will filter just the search results.

Which one do you need?

**Comment by timglabisch** [comment]
the term() has a filter_facet "method", but you missed the "filter" method.

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-facets-filter-facet.html
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-facets.html

A filter facet (not to be confused with a facet filter) allows you to return a count of the hits matching the filter. The filter itself can be expressed using the Query DSL.

**Comment by polyfractal** [comment]
Ah, I see.  The `filter` facet is it's own [distinct facet](https://github.com/polyfractal/sherlock/blob/master/src/Sherlock/components/facets/Filter.php), just like the Terms facet.

It is used something like this:

``` php
$facets = Sherlock::facetBuilder()->Filter()
            ->field('my_field')
            ->filter($filter);
```

**Comment by timglabisch** [comment]
``` php
$facets = Sherlock::facetBuilder()->terms()
            ->field('my_field')
            ->filter($filter);
```

should work, too?

**Comment by polyfractal** [comment]
Nope.  If you want to filter the facet itself, you use `facet_filter`.

**facet_filter**
A `facet_filter` filters the facet context only.  In this example, search results will be "everything", while the facet will only aggregate documents where the user is named `kimchy`

``` json
{
    "query" : {
        "match_all" : {  }
    },
    "facets" : {
        "tag" : {
            "terms" : {
                "field" : "tag",
                "facet_filter" : {
                   "term" : { "user" : "kimchy"}
                 }
            }
        }
    }
}
```

**Top level filter**
A `top level filter` will the search context only.  In this example, search results will be all documents with a user named `kimchy`, while the facet will aggregate all documents regardless of their name.

``` json
{
    "query" : {
        "match_all" : {  }
    },
    "filter" : {
       "term" : { "user" : "kimchy"}
    },
    "facets" : {
        "tag" : {
            "terms" : {
                "field" : "tag"
            }
        }
    }
}
```

**filtered_query**
A `filtered_query` will filter both search results and facets.  So this example will show only documents that are named `kimchy`, and the facet will only aggregate documents with `kimchy` too.

``` json
{
    "query" : {
        "filtered" : {
           "query" : {
              "match_all" : {  }
           },
           "filter" : {
              "term" : { "user" : "kimchy"}
            }
        },
    },  
    "facets" : {
        "tag" : {
            "terms" : {
                "field" : "tag"
            }
        }
    }
}
```

**Filter Facet**
Finally, a `filter facet` is a special type of facet that simply returns the count of documents matching the filter.  It operates just like the Terms facet, except instead of recording the counts of all terms, it only records the counts matching the filter.

In practice it isn't used very often.

``` json
{
    "query" : {
        "match_all" : {  }
    },
    "facets" : {
        "tag" : {
            "filter" : {
                "term" : { "user" : "kimchy"}
            }
        }
    }
}
```
